name: Zealot Issue Watcher

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:   ${{ secrets.TG_CHAT_ID }}
          INTERVAL_MIN: "60"
          MAX_RESULTS: "100"
          PAGINATE_PAGES: "3"
          FILTER_LINKED_PR: "1"
          MAX_TIMELINE_CHECKS: "60"
          TIMELINE_MAX_PAGES: "2"
        run: |
          python watcher.py

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zealot-reports
          path: |
            notify.html
            notify.txt
